import json
import os
import shutil
import zipfile
from pathlib import Path

zip_name = os.environ["ZIP_NAME"]
jar_name = os.environ["JAR_NAME"]
version_number = os.environ["VERSION_NUMBER"]
project_id = os.environ["PROJECT_ID"]

mod_id = "mr_enchantments_encore"
mod_name = "Enchantments Encore"
slug = "enchantments-encore"
description = "Enchantments Encore packaged as a universal data/resource mod."
icon = "enchantments-encore_pack.png"
homepage = f"https://modrinth.com/datapack/{slug}"
sources = f"https://github.com/Explorers-Eden/{slug}"

required = ["data", "LICENSE", "pack.mcmeta", "pack.png"]
missing = [p for p in required if not os.path.exists(p)]
if missing:
    raise FileNotFoundError(f"Missing required files/folders: {', '.join(missing)}")

assets_lang = Path("assets/enchantencore/lang")
data_lang = Path("data/enchantencore/lang")

if assets_lang.exists():
    if data_lang.exists():
        shutil.rmtree(data_lang)
    shutil.copytree(assets_lang, data_lang)
    print("Synced assets/enchantencore/lang -> data/enchantencore/lang")
else:
    print("No assets/enchantencore/lang found, skipping lang sync")


def add_pack_files(zf):
    for folder in ["assets", "data"]:
        if not os.path.exists(folder):
            continue
        for root, _, files in os.walk(folder):
            for file in files:
                full = os.path.join(root, file)
                zf.write(full, os.path.relpath(full, "."))

    for file in ["LICENSE", "pack.mcmeta", "pack.png"]:
        zf.write(file, file)


with zipfile.ZipFile(zip_name, "w", zipfile.ZIP_DEFLATED) as zf:
    add_pack_files(zf)

build = Path("build/universal_mod")
if build.exists():
    shutil.rmtree(build)

(build / "META-INF").mkdir(parents=True)

if os.path.exists("assets"):
    shutil.copytree("assets", build / "assets")
shutil.copytree("data", build / "data")

shutil.copy2("LICENSE", build / "LICENSE")
shutil.copy2("pack.mcmeta", build / "pack.mcmeta")
shutil.copy2("pack.png", build / "pack.png")
shutil.copy2("pack.png", build / icon)

fabric_json = {
    "schemaVersion": 1,
    "id": mod_id,
    "version": version_number,
    "name": mod_name,
    "description": description,
    "authors": [],
    "contact": {
        "homepage": homepage,
        "sources": sources,
    },
    "license": "GPL-3.0-or-later",
    "icon": icon,
    "environment": "*",
    "depends": {
        "fabric-resource-loader-v0": "*"
    }
}

quilt_json = {
    "schema_version": 1,
    "quilt_loader": {
        "group": "com.modrinth",
        "id": mod_id,
        "version": version_number,
        "metadata": {
            "name": mod_name,
            "description": description,
            "contributors": {},
            "contact": {
                "homepage": homepage,
                "sources": sources,
            },
            "icon": icon,
        },
        "intermediate_mappings": "net.fabricmc:intermediary",
        "depends": [
            {
                "id": "quilt_resource_loader",
                "versions": "*",
                "unless": "fabric-resource-loader-v0",
            }
        ],
    }
}

forge_toml = f"""
modLoader = 'lowcodefml'
loaderVersion = '[40,)'
license = 'GPL-3.0-or-later'
showAsResourcePack = false
mods = [
  {{ modId = '{mod_id}', version = '{version_number}', displayName = '{mod_name}', description = '{description}', logoFile = '{icon}', updateJSONURL = 'https://api.modrinth.com/updates/{project_id}/forge_updates.json', credits = 'Generated by Modrinth', authors = '', displayURL = '{homepage}' }},
]
"""

neoforge_toml = f"""
modLoader = 'javafml'
loaderVersion = '[1,)'
license = 'GPL-3.0-or-later'
showAsResourcePack = false
mods = [
  {{ modId = '{mod_id}', version = '{version_number}', displayName = '{mod_name}', description = '{description}', logoFile = '{icon}', updateJSONURL = 'https://api.modrinth.com/updates/{project_id}/forge_updates.json?neoforge=only', credits = 'Generated by Modrinth', authors = '', displayURL = '{homepage}' }},
]
"""

(build / "fabric.mod.json").write_text(json.dumps(fabric_json, separators=(",", ":")), encoding="utf-8")
(build / "quilt.mod.json").write_text(json.dumps(quilt_json, separators=(",", ":")), encoding="utf-8")
(build / "META-INF" / "mods.toml").write_text(forge_toml.strip() + "\n", encoding="utf-8")
(build / "META-INF" / "neoforge.mods.toml").write_text(neoforge_toml.strip() + "\n", encoding="utf-8")

with zipfile.ZipFile(jar_name, "w", zipfile.ZIP_DEFLATED) as zf:
    for root, _, files in os.walk(build):
        for file in files:
            full = Path(root) / file
            zf.write(full, full.relative_to(build).as_posix())

print(f"Created {zip_name}")
print(f"Created {jar_name}")
